#!/bin/bash

# README
# Script for running after an ubuntu kernel update. It copies the kernel,
# uInitrd and meson64_odroidc2.dtb to the multiboot location
# WARNING: This is not a universal working script yet, make sure it is adapted to your system

# We're passed the version of the kernel being installed
inst_kern=$1

UBUNTU_BOOT_DIR="/boot"
ODROID_BOOT_DIR="/media/boot"
MULTIBOOT_DIR="${ODROID_BOOT_DIR}/multiboot"

# checking if /media/boot exists if so, then copy uInitrd there (should be Ubuntu)
if [ -d "${MULTIBOOT_DIR}" ]; then

	# backup old multiboot files
	mv "${MULTIBOOT_DIR}/uInitrd.ubuntu" "${MULTIBOOT_DIR}/uInitrd.ubuntu.bak"
	mv "${MULTIBOOT_DIR}/Image.ubuntu" "${MULTIBOOT_DIR}/Image.ubuntu.bak"
	mv "${MULTIBOOT_DIR}/meson64_odroidc2.dtb.ubuntu" "${MULTIBOOT_DIR}/meson64_odroidc2.dtb.ubuntu.bak"

	# copy new boot files to multiboot
	cp "${ODROID_BOOT_DIR}/uInitrd" "${MULTIBOOT_DIR}/uInitrd.ubuntu"
	cp "${ODROID_BOOT_DIR}/Image" "${MULTIBOOT_DIR}/Image.ubuntu"
	cp "${ODROID_BOOT_DIR}/meson64_odroidc2.dtb" "${MULTIBOOT_DIR}/meson64_odroidc2.dtb.ubuntu"
fi
